service:
    name: deploy-worker-github-action
    config:
      accountId: ${env:a43fcfd4ab6dc2808fde2b85e2f4a8b0}

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers
  
functions:
  worker-deploy:
    name: ${env:worker-script}
    script: ${env:worker-script} 
